import turtle
t = turtle.Turtle()
##wn = turtle.Screen()
##wn.bgcolor('black')
##t.fillcolor('red')
##t.begin_fill()
##t.forward(60)
##t.right(60)
##t.forward(60)
##t.right(60)
##t.forward(60)
##t.right(60)
##t.forward(60)
##t.right(60)
##t.forward(60)
##t.right(60)
##t.forward(60)
##t.right(60)
##t.end_fill()
##
##
##t.color("Chartreuse")
##t.stamp()
##t.penup()
##t.color("pink")
##t.forward(40)
##t.pendown()
##t.stamp()
##t.penup()
##t.color("Crimson")
##t.forward(40)
##t.pendown()
##t.stamp()
##t.penup()
##t.color("maroon")
##t.forward(40)
##t.pendown()
##t.stamp()
##t.penup()
##t.color("green")
##t.forward(40)
##t.pendown()
##t.stamp()
##t.penup()
##t.color("blue")
##t.forward(40)
##t.pendown()
##t.stamp()
##t.penup()
##
##
##t.fillcolor("cyan")
##t.begin_fill()
##t.pendown()
##t.forward(60)
##t.right(72)
##t.forward(60)
##t.right(72)
##t.forward(60)
##t.right(72)
##t.forward(60)
##t.right(72)
##t.forward(60)
##t.right(72)
##t.end_fill()


##t.pendown()
##t.fillcolor("green")
##t.begin_fill()
##t.forward(60)
##t.left(120)
##t.forward(60)
##t.left(120)
##t.forward(60)
##t.left(120)
##t.forward(60)
##t.left(120)
##t.end_fill()


##t.pendown()
##t.fillcolor("pink")
##t.begin_fill()
##t.forward(60)
##t.right(144)
##t.forward(60)
##t.right(144)
##t.forward(60)
##t.right(144)
##t.forward(60)
##t.right(144)
##t.forward(60)
##t.right(144)
##t.end_fill


##
##wn = turtle.Screen()
##wn.bgcolor("light green")
##t.shape("circle")
##t.penup()
##t.color("red")
##t.stamp()
##t.forward(40)
##t.color("orange")
##t.stamp()
##t.forward(40)
##t.color("yellow")
##t.stamp()
##t.forward(40)
##t.color("green")
##t.stamp()
##t.forward(40)
##t.color("blue")
##t.stamp()
##t.forward(40)
##t.color("purple")
##t.stamp()
##t.forward(40)
##t.color("violet")
##t.stamp()
##t.penup()

