import turtle
t = turtle.Turtle()
t.shape('classic')


t.penup()
t.fillcolor('green')
t.begin_fill()
t.circle(100)
t.end_fill()
t.backward(40)
t.fillcolor('blue')
t.begin_fill()
t.circle(100)
t.end_fill()
t.backward(40)
t.fillcolor('yellow')
t.begin_fill()
t.circle(100)
t.end_fill()
t.right(90)
t.forward(50)
t.color('pink')
t.write('Ultimate Coders')
t.forward(50)
